import type { LucideIcon } from 'lucide-react';
import {
    Accessibility,
    Baby,
    Bath,
    BedDouble,
    Beer,
    Bike,
    Briefcase,
    Bus,
    Car,
    CigaretteOff,
    CircleHelp,
    CircleParking,
    Clock,
    Coffee,
    ConciergeBell,
    Croissant,
    Dumbbell,
    Fan,
    Fish,
    Flower2,
    Gamepad2,
    Heater,
    Landmark,
    Laptop,
    Martini,
    Mountain,
    Music,
    PawPrint,
    Plane,
    Refrigerator,
    Sailboat,
    ShowerHead,
    Snowflake,
    Sparkles,
    Sun,
    TreePalm,
    Trees,
    Tv,
    Umbrella,
    Utensils,
    UtensilsCrossed,
    Vault,
    WashingMachine,
    Waves,
    Wifi,
    Wine,
} from 'lucide-react';

/**
 * Icons an admin can assign to an amenity. Only these are bundled (importing
 * every Lucide icon would add ~1,500 icons to the JavaScript bundle). Keep in
 * sync with app/Enums/AmenityIcon.php.
 */
export const amenityIcons: Record<string, LucideIcon> = {
    Wifi,
    Waves,
    CircleParking,
    Coffee,
    Croissant,
    Utensils,
    UtensilsCrossed,
    Wine,
    Martini,
    Beer,
    Dumbbell,
    Sparkles,
    Bath,
    ShowerHead,
    Snowflake,
    Heater,
    Fan,
    PawPrint,
    Accessibility,
    Umbrella,
    Sun,
    TreePalm,
    Trees,
    Flower2,
    Mountain,
    Sailboat,
    Fish,
    Bike,
    Car,
    Bus,
    Plane,
    ConciergeBell,
    BedDouble,
    Baby,
    Tv,
    WashingMachine,
    Refrigerator,
    Vault,
    Briefcase,
    Laptop,
    Gamepad2,
    Music,
    CigaretteOff,
    Clock,
    Landmark,
};

export function amenityIcon(name: string): LucideIcon {
    return amenityIcons[name] ?? CircleHelp;
}
